#!/bin/bash
set -e

if [ ! -d _locales ]; then
	echo 'Run me from the root of the project'
	exit 2
fi

if [ ! -d jquery ]; then
	git clone git://github.com/jquery/jquery.git
	cd jquery
	npm install
else
	cd jquery
fi

git checkout --quiet master
git pull --quiet
git checkout --quiet $(git describe --abbrev=0 --tags)
grunt custom:-ajax,-css,-deprecated,-dimensions,-effects,-event-alias,-offset,-wrap,-sizzle
cp dist/jquery.min.js ../
git checkout --quiet master
cd ..
